"""Ajout champ no

Revision ID: 20951dff972a
Revises: 0dd3a07f94e2
Create Date: 2024-09-18 15:07:34.133722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import oracle

# revision identifiers, used by Alembic.
revision: str = '20951dff972a'
down_revision: Union[str, None] = '0dd3a07f94e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table333')
    op.drop_table('employees')
    op.drop_table('newtable')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newtable',
    sa.Column('column1', sa.VARCHAR(length=100), nullable=True)
    )
    op.create_table('employees',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name='employees_pk')
    )
    op.create_table('table333',
    sa.Column('column1', sa.INTEGER(), nullable=False),
    sa.Column('column2', oracle.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('column1', name='table333_pk')
    )
    # ### end Alembic commands ###
