"""Ajout champ no OK

Revision ID: 9f03992f0a03
Revises: 20951dff972a
Create Date: 2024-09-18 15:27:32.494632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f03992f0a03'
down_revision: Union[str, None] = '20951dff972a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('no', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'no')
    # ### end Alembic commands ###
